FROM python:3.14-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV FLASK_APP=app.py \
    FLASK_ENV=development \
    FLASK_DEBUG=1

EXPOSE 5000

CMD ["flask", "run", "--port=0.0.0.0", "--port=5000"]